spring.application.name=books-management-app

# database setup for H2 Database (memory db)
#spring.datasource.url=jdbc:h2:mem:testdb
#
#spring.h2.console.path=/h2-console
#spring.h2.console.enabled=true
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.generate.ddl=true

# -------------------------------------------------------------

# Database setup for MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/books_db
spring.datasource.username=book_user
spring.datasource.password=Books@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
